#+title: Readme

土  7  6 2025 21:38

Exploring / remaking TidalCycles in SuperCollider

* Part 1: Scheduling events in a cycle
/First steps: Scheduling and un-scheduling a full tidal cycle pattern while it is running, at any point./

/This is only a short preliminary study, and is incomplete./

Use absolute time with a Routine (fork).
Not TempoClock.

Figure out how to replace unscheduled events with new ones, and continue with scheduling the next due event during the cycle, when replacing the entire pattern.

- Use absolute time: Clock.seconds.
- Calculate the absolute time of all events in the pattern.
- Find the next event, i.e. the next event whose absolute time is greater than Clock.seconds.
- Schedule the next event at event.abstime - Clock.seconds
- Continue with scheduling all events till end of cycle

Using class =TidalCycle= to implement this.

* Part 2 Parsing Tidal syntax, specifically mini-notation

Class TidalParser is a first draft of how to parse TidalCycles mini-notation.  (Written by Cursor AI of cursor.com, contains many mistakes, basically useful only as a starting point for writing a parser.)
